"""Module for combining serializers"""
from main_app.rest.Department_serialize import DepartmentSerialize
from main_app.rest.Employee_serialize import EmployeeSerialize
from main_app.rest.Level_serialize import LevelSerialize
from main_app.rest.Project_serialize import ProjectSerialize
from main_app.rest.ProjectList_serialize import ProjectListSerialize
from main_app.rest.Status_serialize import StatusSerialize
from main_app.rest.StatusVacation_serialize import StatusVacationSerialize
from main_app.rest.Task_serialize import TaskSerialize
from main_app.rest.Timesheet_serialize import TimesheetSerialize
from main_app.rest.TypeVacation_serialize import TypeVacationSerialize
from main_app.rest.Vacation_serialize import VacationSerialize
from main_app.rest.User_serialize import UserSerialize
from main_app.rest.BlockColor_serialize import BlockColorSerialize
from main_app.rest.PhotoModel_serialize import PhotoModelSerialize
