# Generated by Django 4.0.3 on 2022-04-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Department names',
                'db_table': 'Department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40, null=True)),
                ('photo', models.ImageField(height_field=150, upload_to='', width_field=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
            options={
                'verbose_name': 'Employee information',
                'db_table': 'employees',
                'ordering': ['level', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Level names',
                'db_table': 'Level',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Project names',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Status names',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='StatusVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vacation', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Status vac names',
                'db_table': 'StatusVacation',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Task names',
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='TypeVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vacation', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Types vacation',
                'db_table': 'TypeVacation',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('photo_approve', models.ImageField(null=True, upload_to='')),
                ('comment_emp', models.CharField(max_length=200, null=True)),
                ('comment_appr', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
                ('status_vacation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.statusvacation')),
                ('type_vacation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.typevacation')),
            ],
            options={
                'verbose_name': 'Vacation information',
                'db_table': 'Vacation',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time', models.IntegerField(null=True)),
                ('task_date', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.task')),
            ],
            options={
                'verbose_name': 'Timesheet information',
                'db_table': 'Timesheet',
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
            options={
                'verbose_name': 'List of projects',
                'db_table': 'ProjectList',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.level'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.status'),
        ),
    ]
