# Generated by Django 4.0.3 on 2022-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_employee_id_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(height_field=150, null=True, upload_to='', width_field=150),
        ),
    ]
