# Generated by Django 4.0.3 on 2022-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='task_date',
            field=models.DateField(null=True),
        ),
    ]
