# Generated by Django 3.1.4 on 2022-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20220430_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=10, unique=True)),
                ('progress_color', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
