# Generated by Django 3.1.4 on 2022-05-01 09:34

from django.db import migrations

def data_for_db(apps, schema_editor):
    BC = apps.get_model('main_app', 'BlockColor')
    BC.objects.bulk_create([
        BC(background_color='#fee4cb;', progress_color='#ff942e;'),
        BC(background_color='#e9e7fd;', progress_color='#4f3ff0;'),
        BC(background_color='#87a5ff;', progress_color='#096c86;'),
        BC(background_color='#ffd3e2;', progress_color='#df3670;'),
        BC(background_color='#fcfbac;', progress_color='#d6d40d;'),
        BC(background_color='#ffbaf0;', progress_color='#b52696;'),
        BC(background_color='#c8f7dc;', progress_color='#34c471;'),
        BC(background_color='#d5deff;', progress_color='#4067f9;'),
        BC(background_color='#f7daab;', progress_color='#99712f;'),
        BC(background_color='#a2f5e9;', progress_color='#18baa2;'),
    ])


def delete_data(apps, schema_editor):
    Department = apps.get_model('department_app', 'Department')

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_blockcolor'),
    ]

    operations = [migrations.RunPython(data_for_db, delete_data)
    ]


