# Generated by Django 3.1.4 on 2022-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220501_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.IntegerField(null=True),
        ),
    ]
