# Generated by Django 3.1.4 on 2022-05-02 13:02

from django.db import migrations

def data_for_db(apps, schema_editor):
    SV = apps.get_model('main_app', 'StatusVacation')
    SV.objects.bulk_create([
        SV(status_vacation='Approved'),
        SV(status_vacation='Requires supplement'),
        SV(status_vacation='Denied'),
        SV(status_vacation='Wait for approval'),
    ])
    TV = apps.get_model('main_app', 'TypeVacation')
    TV.objects.bulk_create([
        TV(type_vacation='Sick leave'),
        TV(type_vacation='Paid leave'),
        TV(type_vacation='Unpaid leave'),
        TV(type_vacation='Day off'),
    ])


def delete_data(apps, schema_editor):
    StatusVacation = apps.get_model('department_app', 'StatusVacation')

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_employee_manager'),
    ]

    operations = [migrations.RunPython(data_for_db, delete_data)
    ]
