# Generated by Django 3.1.4 on 2022-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20220502_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='comment_appr',
        ),
        migrations.AlterField(
            model_name='vacation',
            name='comment_emp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='photo_approve',
            field=models.ImageField(null=True, upload_to='vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
