# Generated by Django 3.1.4 on 2022-05-04 08:27

from django.db import migrations

def data_for_db(apps, schema_editor):
    PR = apps.get_model('main_app', 'Project')
    PR.objects.bulk_create([
        PR(project_name='EPAM'),
    ])
    TV = apps.get_model('main_app', 'Task')
    TV.objects.bulk_create([
        TV(task_name='Sick leave'),
        TV(task_name='Paid leave'),
        TV(task_name='Unpaid leave'),
        TV(task_name='Day off'),
    ])


def delete_data(apps, schema_editor):
    StatusVacation = apps.get_model('department_app', 'StatusVacation')

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_photomodel'),
    ]

    operations = [migrations.RunPython(data_for_db, delete_data)
    ]
