# Generated by Django 3.1.4 on 2022-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20220504_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-start_date'], 'verbose_name': 'Vacation information'},
        ),
        migrations.AddField(
            model_name='projectlist',
            name='workload',
            field=models.FloatField(default=0.0),
        ),
    ]
