from main_app.service.mainpage_service import MainPageTemplate, TimesheetDelete
from main_app.service.activity_service import ActivityPageTemplate
from main_app.service.activity_service import TaskDelete, TaskCreate, TaskEdit
from main_app.service.notification_service import NotificationPageTemplate, VacationCreate, VacationInfo, VacationDec
from main_app.service.settings_service import SettingsPageTemplate