"""Module for combining models"""
from main_app.models.Department import Department
from main_app.models.Employee import Employee
from main_app.models.Level import Level
from main_app.models.Project import Project
from main_app.models.ProjectList import ProjectList
from main_app.models.Status import Status
from main_app.models.StatusVacation import StatusVacation
from main_app.models.Task import Task
from main_app.models.Timesheet import Timesheet
from main_app.models.TypeVacation import TypeVacation
from main_app.models.Vacation import Vacation
from main_app.models.BlockColor import BlockColor
from main_app.models.PhotoModel import PhotoModel
